allowBuilds:
  '@biomejs/biome': false
  '@tailwindcss/oxide': false
engineStrict: true

patchedDependencies:
  '@material/material-color-utilities': 'patches/@material__material-color-utilities.patch'
